### PR TITLE
Update Making a POST request from a standalone client in httpserver.m…

### PR DESCRIPTION
**Pull request by zakariaz**
What i learned in the previous tutorials is that an async function or method returns a `Future` which complete with a value so i think the section explaining the behavior of the `post()` method should use the same terminology so new people like me who are learning Dart will not be confused.

### CODE REVIEW

**Review by kwalrath — APPROVED** [review]
Much better, thanks!

**Comment by kwalrath** [comment]
It looks like this is a PR against your repo, not ours. One possible fix is to just edit the page by clicking the doc icon at the upper right and then using the GitHub edit UI.

**Comment by zakariaz** [comment]
Sorry to be late, i was quite busy.
You are welcome, I am glad to help

**Comment by kwalrath** [comment]
We still need to get your change into the dart-lang/site-www repo. You could to git magic to create a PR that merges the change from your repo, or (since the change is to only one file) it might be easier to edit https://github.com/dart-lang/site-www/blob/master/src/_tutorials/server/httpserver.md and create a new PR.

Your choice!

**Comment by zakariaz** [comment]
HI,
Sorry @kwalrath  to respond 15 days later, i didn't see the issue with my commit.  i saw that the pull request was successfully merged. i deleted the branch. i don't understand the problem. could you explain what didn't allow the merge, please. have i to merge the branch to master in my repo then merge it here or something like that ?

**Comment by zakariaz** [comment]
HI,
Sorry @kwalrath  to respond 15 days later, i didn't see the issue with my commit.  i saw that the pull request was successfully merged. i deleted the branch. i don't understand the problem. could you explain what didn't allow the merge, please. have i to merge the branch to master in my repo then merge it here or something like that ?

**Pull request merged**
